# Generated by Django 5.2.4 on 2025-08-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt_txt", models.DateTimeField()),
                ("city", models.CharField(max_length=100)),
                ("temp", models.FloatField()),
                ("humidity", models.FloatField()),
                ("pressure", models.IntegerField()),
                ("speed", models.FloatField()),
                ("visibility", models.FloatField()),
            ],
        ),
    ]
