# Generated by Django 5.2.4 on 2025-08-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("storm", "Storm Warning"),
                            ("rain", "Heavy Rain"),
                            ("heat", "Heat Wave"),
                            ("cold", "Cold Wave"),
                            ("fog", "Fog Alert"),
                            ("wind", "High Wind"),
                            ("flood", "Flood Warning"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="country",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="feels_like",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="temp_max",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="temp_min",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="weather_description",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="weather_main",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_deg",
            field=models.FloatField(default=0.0),
        ),
    ]
