# Generated by Django 5.2.4 on 2025-08-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_weatheralert_weatherdata_country_and_more"),
    ]

    operations = []
