# Generated by Django 5.2.4 on 2025-08-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0003_auto_20250803_2217"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("analysis_date", models.DateField()),
                ("avg_temp", models.FloatField()),
                ("max_temp", models.FloatField()),
                ("min_temp", models.FloatField()),
                ("avg_humidity", models.FloatField()),
                ("total_precipitation", models.FloatField(default=0.0)),
                ("dominant_weather_type", models.CharField(default="", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-analysis_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="weatheralert",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="weatherdata",
            options={"ordering": ["-dt_txt"]},
        ),
        migrations.AddField(
            model_name="weatheralert",
            name="affected_area",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="weatheralert",
            name="recommendations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="weatheralert",
            name="source",
            field=models.CharField(default="System Generated", max_length=100),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="cloudiness",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="precipitation",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="uv_index",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="weather_subtype",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="weather_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="weatheralert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("storm", "Storm Warning"),
                    ("rain", "Heavy Rain"),
                    ("heat", "Heat Wave"),
                    ("cold", "Cold Wave"),
                    ("fog", "Fog Alert"),
                    ("wind", "High Wind"),
                    ("flood", "Flood Warning"),
                    ("snow", "Snow Alert"),
                    ("thunderstorm", "Thunderstorm"),
                    ("dust", "Dust Storm"),
                    ("smog", "Smog Alert"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="weatheralert",
            index=models.Index(
                fields=["city", "is_active"], name="weather_wea_city_6e2515_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weatheralert",
            index=models.Index(
                fields=["alert_type", "severity"], name="weather_wea_alert_t_5b595d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weatherdata",
            index=models.Index(
                fields=["city", "dt_txt"], name="weather_wea_city_58333a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weatherdata",
            index=models.Index(
                fields=["weather_type"], name="weather_wea_weather_29511b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weatherdata",
            index=models.Index(fields=["temp"], name="weather_wea_temp_317666_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="weatheranalysis",
            unique_together={("city", "analysis_date")},
        ),
    ]
