# Generated by Django 5.2.4 on 2025-08-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnergyAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("high_consumption", "High Energy Consumption"),
                            ("anomaly", "Anomaly Detection"),
                            ("cost_warning", "Cost Warning"),
                            ("efficiency", "Efficiency Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnergyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_id", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                ("device_type", models.CharField(max_length=100)),
                ("device_name", models.CharField(max_length=100)),
                ("room", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("power_watt", models.FloatField()),
                ("user_present", models.BooleanField()),
                ("activity", models.CharField(max_length=100)),
                ("indoor_temp", models.FloatField()),
                ("outdoor_temp", models.FloatField()),
                ("humidity", models.FloatField()),
                ("light_level", models.FloatField()),
                ("day_of_week", models.IntegerField()),
                ("hour_of_day", models.IntegerField()),
                ("price_kwh", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EnergyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("random_forest", "Random Forest"),
                            ("linear_regression", "Linear Regression"),
                            ("gradient_boosting", "Gradient Boosting"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model_file", models.FileField(upload_to="models/")),
                ("accuracy", models.FloatField()),
                ("mse", models.FloatField()),
                ("mae", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
